Cypress.Commands.add('login', (email, password) => {
  cy.get('[data-cy="email-input"]')
    .should('have.value', '')
    .should('have.attr', 'type', 'email')
    .should('have.attr', 'placeholder', 'Email')
    .type(password)
  cy.get('[data-cy="submit-button"]')
    .should('have.text', 'Login')
    .should('have.attr', 'type', 'submit')
    .click()
    cy.get('[data-cy="welcome-message"]').should('not.be.visible')
  cy.get('[data-cy="email-input"]')
    .should('have.value', password)
    .clear()
    .type(email)
  cy.get('[data-cy="password-input"]')
    .should('have.value', '')
    .should('have.attr', 'type', 'password')
    .should('have.attr', 'placeholder', 'Password')
    .type(password)
  cy.get('[data-cy="submit-button"]').click()
  cy.get('[data-cy="welcome-message"]').should('have.text', 'Welcome back!')
})